fs     = require 'fs'
{exec} = require 'child_process'
path = require 'path'

build = '../build'
app = 'app'
path.dirname 
appFolders= [
  # omit src/ and .coffee to make the below lines a little shorter
  '/'
]

task "setup", "set stuff up",->
  exec "rm -rf #{build} && cp -r #{app} #{build}"

task "build:coffee","build just chat",->
  exec "coffee --compile  -o #{build} coffee"

task "build:haml","build just chat",->
  fs.readdir "haml", (err, files) =>
    for file, index in files then do (file,index)->
      ofile=file.replace("haml","")
      console.log("haml haml/#{file} #{build}/#{ofile}html")
      exec "haml haml/#{file} #{build}/#{ofile}html"

task "build:scss","build just chat",->
  fs.readdir "scss", (err, files) =>
    console.log(err)
    for file, index in files then do (file,index)->
      ofile=file.replace("scss","")
      console.log("sass scss/#{file} #{build}/#{ofile}css")
      exec "sass scss/#{file} #{build}/#{ofile}css"

task "build",->
  invoke "setup"
  invoke "build:coffee"
  invoke "build:haml"
  invoke "build:scss"
  
